### ISSUE TITLE
 I can't access

### ISSUE THREAD

**Issue by ferstpetr777** [n4ze3m/page-assist#1]
Nazim Afternoon, I can't access your remarkable application, I get an error ( Failed to fetch ) , please help me to connect to this Chrome extension. 
my email is rtep1976@me.com. Thank you!
<img width="1440" alt="Снимок экрана 2024-01-25 в 17 17 17" src="https://github.com/n4ze3m/page-assist/assets/133219575/1c9c5f02-6f14-4359-b59d-9b8ee40a893b">

**Comment by n4ze3m** [comment]
Hey, sorry, the server isn't running anymore :/
