### ISSUE TITLE
Unable to access services on the local network

### ISSUE THREAD

**Issue by wynemo** [n4ze3m/page-assist#10]
<img width="837" alt="image" src="https://github.com/n4ze3m/page-assist/assets/1314428/ac988863-489a-4173-8fca-84dcbd79c388">

**Comment by n4ze3m** [comment]
Hey, thanks for reporting. Usually, it will work. I will look into it. Thanks

**Comment by wynemo** [comment]
it's related to https://github.com/ollama/ollama/issues/2335, 

using `OLLAMA_ORIGINS=http://10.113.6.143 OLLAMA_HOST=0.0.0.0 ollama serve`, it works now

**Comment by n4ze3m** [comment]
I know about that issue, which is why I rewrote the request with a custom origin. Which browser are you using, Chrome?

**Comment by wynemo** [comment]
yeah，i'm using chrome
