### ISSUE TITLE
Shortcuts for Web UI and Sidebar on Firefox

### ISSUE THREAD

**Issue by rolflessing** [n4ze3m/page-assist#102]
Shortcuts for Web UI and Sidebar on Firefox:
- do not work on Firefox (at least on Windows 11) and
-  are not configurable (at least on Windows 11)

**Comment by n4ze3m** [comment]
Hey, I'm using Firefox on Windows. This is how I configure shortcuts.

https://github.com/n4ze3m/page-assist/assets/39720973/e2a4a2be-9350-4115-acef-15fc62b24868
