### ISSUE TITLE
Computer without gpu or weak gpu

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/page-assist#11]
Your project is excellent, but it doesn't work on my laptop, which isn't powerful enough.

Why don't you suggest OpenRouter, which would be perfect with their free models?

**Comment by n4ze3m** [comment]
Hey, Page Assist won't support third-party providers, but my new project, 'Dialoqbase Lite,' similar to Page Assist, will support all third-party models. It will be released within two weeks.

**Comment by comeback01** [comment]
You're the best!

**Comment by n4ze3m** [comment]
Hey :) Here is a similar extension that supports third-party AI provers.

https://chromewebstore.google.com/detail/dialoqbase-lite-a-sidepan/fhdonbcklgialicndhegpkkhhekafglb?hl=en&authuser=2

![image](https://github.com/n4ze3m/page-assist/assets/39720973/7fd6e9f2-1190-4429-b8d7-1a0a42729c65)

**Comment by comeback01** [comment]
Thanks, you are the best
