### ISSUE TITLE
Prompt and knowledge lost after upgrade

### ISSUE THREAD

**Issue by zapzap-77** [n4ze3m/page-assist#113]
Hello,

I was using the 1.1.10 version of the Chrome extension and found there's now a version 1.1.11.
I looked for a way to upgrade but did not find and information about this topic.

So I removed the extension 1.1.10 and installed the 1.1.11 successfully.

Now I find that the knowledge documents added to page-assist as well as the prompts are gone.

It would be nice to be able to store these data somewhere, or at least having an export functionality.

**Comment by n4ze3m** [comment]
Hey, sorry about that. Your browser usually updates extension to the latest version automatically. You might need to close and reopen the browser to reflect the new changes i guess https://stackoverflow.com/questions/74635848/auto-update-in-chrome-extensions.

There is an option in the general settings to export chats, knowledge bases, and prompts. You can also import them.

**Comment by zapzap-77** [comment]
Looks like I started this case a bit too fast.   Thanks for those infos.

**Comment by n4ze3m** [comment]
It's okay; Firefox has an option to update extensions manually, but Chromium browsers don't have a similar feature. :/
