### ISSUE TITLE
[ENHANCEMENT] The sidebar input dialog supports drag-and-drop input.

### ISSUE THREAD

**Issue by Leroy-X** [n4ze3m/page-assist#116]
I recorded a video to explain it， looking forward to enhancing it.

Furthermore, I believe that in the future being able to drag and drop the links or files, such as PDFs, TXTs, CSVs, and Markdown files, will be fantastic.

Thank you very‘ much!

https://github.com/n4ze3m/page-assist/assets/13515498/bae72eac-4e83-4fe4-b271-600ee061c241

**Comment by n4ze3m** [comment]
Hey, thanks for the suggestions. This was a bug; we will fix it in the next release. Thanks for noticing it

**Comment by n4ze3m** [comment]
The latest version allows you to drag and drop text. Let me know if you still have any issues. Thanks!
