### ISSUE TITLE
[SUGGESTION] When opening a previous chat, set the current model to the last one used in that chat.

### ISSUE THREAD

**Issue by Lathanao** [n4ze3m/page-assist#122]
All is in the title.
When open a previous chat page form the side panel, is it possible set the current model as the last one use the page?

Thanks again for this great extension, I use it every day!

**Comment by n4ze3m** [comment]
The latest version supports this. You need to enable this option for it to work. I'm closing this issue. If you have any further questions, feel free to open a new one.

![image](https://github.com/user-attachments/assets/7518c0ff-5b10-4b10-88af-c7b834673ce6)
