### ISSUE TITLE
Hotkey setting request (feature request for compatibility with Linux Firefox)

### ISSUE THREAD

**Issue by stuzenz** [n4ze3m/page-assist#139]
Hi Muhammed

Tidy code and beautiful UX with the extension - congratulations.

I have just installed it and noticed that for firefox on Linux that the hotkey ctrl-shift-p is the same hotkey that firefox uses to open a private window. 

If you can find time, is it possible for you to make the hotkeys user defined in the settings menu?

Great work - well impressed?

**Comment by n4ze3m** [comment]
Thanks, I will add an option for Firefox in the next update. I thought there would be an option like in Chromium browsers to change extension commands

eg:

![image](https://github.com/n4ze3m/page-assist/assets/39720973/d440578d-da94-4ffa-b6eb-0ca0b6721284)

**Comment by LFd3v** [comment]
I do not mean to disturb, but actually there is an option to change shortcuts in Firefox (screenshot from Floorp, which is based on Firefox ESR at this moment, running on ArchLinux/Garuda):

![Screenshot from 2024-07-16 18-45-24](https://github.com/user-attachments/assets/9fd6069d-311f-48c9-831f-d1644901aef4)

**Comment by n4ze3m** [comment]
Thank you, I didn't know about this
