### ISSUE TITLE
[bug] The input box does not support Chinese input method for firefox ext, chrome not tested

### ISSUE THREAD

**Issue by lpaging** [n4ze3m/page-assist#142]
![PixPin_2024-07-15_21-26-10](https://github.com/user-attachments/assets/03908733-c95d-4d1d-9ec2-f56b6a945319)
when I try to input with chinese input method, only letters show up. no matter sogou pinyin or microsoft pinyin (windows 11 default chinese input method). 
but i can paste chinese into the input box with ctrl+c/ctrl+v.
need to method that, microsoft ABC (Windows 7 chinese input method) can input Chinese characters directly in the input box, but not that smooth

could you please fix that, thank you

**Comment by n4ze3m** [comment]
Hey, thanks for reporting this issue. I will fix it. Do you have the same issue on Chrome as well? If you can test it on Chrome, please give me feedback. I released a similar fix a few months ago, but I haven't tested it on Firefox yet.

**Comment by lpaging** [comment]
hey, chrome don't have this bug, i can type chinese directly.
