### ISSUE TITLE
Bug or [SUGGESTION] RAG document limit

### ISSUE THREAD

**Issue by clickbrain** [n4ze3m/page-assist#151]
I fed a large number of markdown files into a RAG knowledge base, but it only seems to have processed 10 files. Is there a limit on the number of files for RAG or is this a bug of some kind?

**Comment by n4ze3m** [comment]
It is not a bug. I have added a limit because everything happens inside the browser, and I don't want to slow down the browser by processing a huge amount of files. I might add settings to update the limit; by default, I think it is 10

**Comment by razvanab** [comment]
So, this is why the extension seems to slow down with some documents added to the rag. I was about to add an issue for this.

**Comment by clickbrain** [comment]
OK. I am running browser on M3 with 36gb RAM and the LLM/Ollama is running on an M2 Studio with 64GB of Ram and processing text/markdown files. Would love the option to set the number of files or have unlimited and see how it does.

**Comment by n4ze3m** [comment]
Hey, you can now increase the file limit from the RAG settings

![image](https://github.com/user-attachments/assets/75a77577-138e-4bad-8380-d52b0acb3a31)

**Comment by clickbrain** [comment]
Awesome! Thank you!
