### ISSUE TITLE
[Suggestion] Summary/Key Moments

### ISSUE THREAD

**Issue by oatmealm** [n4ze3m/page-assist#160]
Kagi has a nice, and minimalist, service to get a summary/key moments extracted from a given link. I'm thinking it'd be nice to add/replace the page-assist's menu option [open copilot to chat] with something more specific, or at least activate "chat with page" by default, because I guess that's what users want to to do most of the time?

https://kagi.com/summarizer/index.html

**Comment by n4ze3m** [comment]
Hello, this feature is in Copilot. You need to disable 'Chat with website using vector embeddings' and adjust the context size to fit the model you are using. Here is an example

https://github.com/user-attachments/assets/0e67bd75-04ef-455c-9e38-843eeefbeb0b

**Comment by oatmealm** [comment]
Time too close as far as I'm concerned :)
