### ISSUE TITLE
Unable to enter Chinese characters

### ISSUE THREAD

**Issue by sumsliu** [n4ze3m/page-assist#162]
Unable to enter Chinese characters，please fix the problem, thanks!

**Comment by n4ze3m** [comment]
Hello, thank you for reporting this. Are you using Firefox?

**Comment by nothingness0db** [comment]
Yes, Firefox nightly is being used, and Chinese characters cannot be entered

**Comment by maxela-2001** [comment]
Also present in Firefox 129.0 Stable.

**Comment by n4ze3m** [comment]
I'm trying to debug the issue. Could you try using Page Assist on Chrome to see if the issue occurs there as well?

**Comment by maxela-2001** [comment]
> I'm trying to debug the issue. Could you try using Page Assist on Chrome to see if the issue occurs there as well?

It works alright in Chrome 127.0 Stable.

**Comment by n4ze3m** [comment]
Hey guys, the latest version (1.2.2) has resolved the issue with IME typing on Firefox. Please let me know if you still encounter any problems. Thanks!

https://github.com/user-attachments/assets/da0fff57-422c-4db2-af95-009c2272070c
