### ISSUE TITLE
[Feature request] GPU layers setting for the model.

### ISSUE THREAD

**Issue by razvanab** [n4ze3m/page-assist#168]
In Ollama, there are these settings, "num_gpu <int> The number of layers to send to the GPU," that, at least for me, made the model respond faster.
Can you please add it to Ollama Settings > Model Settings. ?

Thank you.

**Comment by n4ze3m** [comment]
Hey, `num_gpu` has been added in the 1.2.1 update

**Comment by razvanab** [comment]
Great! Thank you.
