### ISSUE TITLE
Text is not selectable in Firefox Sidebar

### ISSUE THREAD

**Issue by gerroon** [n4ze3m/page-assist#169]
Hi

It would be nice if we can select the text in the sidebar just like in the Chrome version. I found an answer but I am not a Js dev I would not know how to fix this.

https://discourse.mozilla.org/t/cant-select-text-displayed-in-the-sidebar/90833

```
 think text selection might be disabled by the browser style (see Browser styles on MDN 2). By default, sidebars also use the browser’s stylesheets for extensions which, among other things, disables text selection.

You can opt-out of this by specifying browser_style: false in your extension’s manifest.json like so:

{
    "manifest_version": 2,
    "name": "Context Search",

    "sidebar_action": {
        "browser_style": false,
        ...
    },
    ...
}

```

**Comment by n4ze3m** [comment]
Hey, thanks for searching for a solution. I already implemented it, but unfortunately, there's a bug in the framework I'm using that doesn't automatically include browser_style in the manifest file. Anyway, I'll add it manually from the next version onwards. :)

**Comment by gerroon** [comment]
Thank you, this is awesome, not the FF addon is feature parity with Crome one thanks
