### ISSUE TITLE
Error Unexpected end of JSON input

### ISSUE THREAD

**Issue by robertszabov** [n4ze3m/page-assist#175]
Hi,

When modifying Page assist - Settings on windows Edge - i got this on Windows 11 - Edge browser 
Error 
Unexpected end of JSON input

i didnt touch any Json file after Edge extension install.

**Comment by n4ze3m** [comment]
Hey, sorry about that. Which setting did you try to change when you got this error? I'll look into it

**Comment by robertszabov** [comment]
Hey. 
You shouldn't sorry anything :)  - we should Thank You for your amazing work!  :)
Click on Settings then Manage Model.

![image](https://github.com/user-attachments/assets/3b21a462-9518-4af3-936e-0ba00552c1f3)


then deleting one of the model shows this:

![image](https://github.com/user-attachments/assets/3aa73a88-07da-4cef-a31a-addf010cbdd4)

**Comment by n4ze3m** [comment]
Ah, got it. I’ll fix it in the 1.2.2 release.
