### ISSUE TITLE
[Feature] Store multiple Ollama instances with individual settings

### ISSUE THREAD

**Issue by colin-campbell** [n4ze3m/page-assist#184]
As part of working on [this issue](https://github.com/n4ze3m/page-assist/issues/178), it came to me that if one is using authentication on multiple different Ollama instances, with different authentication providers, client ids, IdP URL's etc , it would be beneficial to store all the settings together with the Ollama Url and allow the user to select from saved  instances.

In fact this might be a beneficial enhancement anyway - to save with the origin URL settings etc.

Any feedback on this idea?

**Comment by n4ze3m** [comment]
Once support for OpenAI-compatible endpoints is added, it will be easy to integrate the new Ollama endpoint, as Ollama is now OpenAI-compatible

**Comment by n4ze3m** [comment]
Now you can add multiple Ollama instances via OpenAI API-compatible settings. :)
