### ISSUE TITLE
[Bug] AI generated title is not used when sharing a chat

### ISSUE THREAD

**Issue by spj2401Dev** [n4ze3m/page-assist#189]
The AI generated title is used in the sidebar, but when sharing it just reuses the question. In my opinion it should use the AI generated title by default.

![grafik](https://github.com/user-attachments/assets/de3b43ae-3067-4a69-9534-32d5dc6c9178)
![grafik](https://github.com/user-attachments/assets/e2d2abe0-08df-4d5d-aec3-43f118a0bd13)

**Comment by spj2401Dev** [comment]
Amazing. Thank you so much for all your efforts. I love the new AI title feature.

**Comment by n4ze3m** [comment]
This issue has been resolved in version 1.2.4. I'm closing this, but feel free to reopen it if you still face the issue
