### ISSUE TITLE
Clear all in chat history section

### ISSUE THREAD

**Issue by nonetrix** [n4ze3m/page-assist#194]
It would be great if there was a button to clear all chat history instead of one by one deleting all of them, also maybe a auto delete feature after a couple of days as a setting would be great

**Comment by n4ze3m** [comment]
Hey, you can delete the entire chat history by going to Settings. I will add this to the sidebar as well

![image](https://github.com/user-attachments/assets/19189b8a-1d08-4aef-aa46-6b4b11564c9f)
