### ISSUE TITLE
Feature request: Customizable search engine

### ISSUE THREAD

**Issue by ghost** [n4ze3m/page-assist#20]
By supporting custom search engines like DuckDuckGo and SearXNG in RAG, this can help users achieve better privacy.

**Comment by n4ze3m** [comment]
Will add it. The current internet search is an experiment. The upcoming version will add more features and search engines.

**Comment by Fau57** [comment]
AWESOME, sorry i wasn't sure where to say this but i absolutely love this project! THANKS!

**Comment by n4ze3m** [comment]
Hey, version 1.1.1 now supports DuckDuckGo as a search engine.

**Comment by Fau57** [comment]
could presearch be used? 
personally a big fan of Decentralization.
If its too big or tedious i can try to figure it out

**Comment by n4ze3m** [comment]
This is the first time I'm hearing about Presearch; I will add it in the upcoming updates

**Comment by Fau57** [comment]
awesome! As far as I understand or in my experience has been in anything where I just need to add them the URL basically to make it function it just does function so I don't imagine you have to do too much work they seem to have presented the customer and with them a pretty easy to use product it's not like you have to figure out how all the decentralized stuff works I hope

**Comment by ricewind100** [comment]
thanks for this great work
would it be possible to add local searxng as a Search Engine?
