### ISSUE TITLE
Allow fallback providers who use OpenAIChat API format

### ISSUE THREAD

**Issue by aiseei** [n4ze3m/page-assist#203]
Really enjoy using your extension - keeping it lightweight is a great strategy. 
I think it might be super beneficial to leverage the OPENAI Chat API format to allow users to maintain a fallback of api end points/models to leverage off self hosted llama.cpp or even Groq api etc.  

Let me know your thoughts. 

Thanks!

**Comment by n4ze3m** [comment]
Yes, it is already in progress and will hopefully be released this month. In #197, you can easily configure any OpenAI API format provider and use it
