### ISSUE TITLE
Feature request: i18n

### ISSUE THREAD

**Issue by Mindires** [n4ze3m/page-assist#21]
I'd be delighted to offer both Simplified Chinese and Traditional Chinese localization support for this plugin, provided that you keep the localization route reserved.

**Comment by n4ze3m** [comment]
This is so nice. I will add i18n in the next release.

**Comment by n4ze3m** [comment]
Hey, I18n is now possible. If you would like to add a language, please feel free to open a PR.

There are two locale folders: one is for the application, and the other is for Chrome.
