### ISSUE TITLE
korean support

### ISSUE THREAD

**Issue by hkjang** [n4ze3m/page-assist#212]
All responses in page assist chat are in English. Can you help me get the chatbot to respond in Korean?

**Comment by n4ze3m** [comment]
I will add Korean to i18n in the next version. For the chat case, you can set the system prompt, and you can also edit prompts from the 'Manage Prompts' section.

![image](https://github.com/user-attachments/assets/2df57a8b-49fd-47b6-85eb-41a9409f0e94)

![image](https://github.com/user-attachments/assets/b7883ff8-6497-4b94-9d43-e7c5e00a525e)

![image](https://github.com/user-attachments/assets/16711fda-a923-4f93-a355-6e2fd823bf63)

![image](https://github.com/user-attachments/assets/625f3f7f-4af7-4529-a1a3-2ce4a2360336)

**Comment by n4ze3m** [comment]
For the RAG case, go to the RAG settings, scroll to the bottom, and you can edit the system prompt there


![image](https://github.com/user-attachments/assets/52c6acc1-5507-4f0b-9bf1-f4bf00f8bb66)

**Comment by hkjang** [comment]
Thank you for improving the features and providing a user guide.
