### ISSUE TITLE
Enhancement please. Offer Two URLS FOR Multiple devices running ollama on different ports

### ISSUE THREAD

**Issue by RitchZoeSquad** [n4ze3m/page-assist#221]
Enhancement please. Offer Two URLS FOR Multiple devices running ollama on different ports

**Comment by n4ze3m** [comment]
I will add Ollama as an option here, which will dynamically load models like the default one :)

![image](https://github.com/user-attachments/assets/b5b17413-d818-4ab8-ac58-5a12b93f03c7)

**Comment by n4ze3m** [comment]
Now you can add multiple Ollama instances via OpenAI API-compatible settings. :)

**Comment by RitchZoeSquad** [comment]
> Now you can add multiple Ollama instances via OpenAI API-compatible settings. :)

I meant to be able to pull two different instances running ollama.


I have two pcs and would like to be able to see both pcs models so that I have the capability to make more asynchronous calls.
