### ISSUE TITLE
Over usage same web data

### ISSUE THREAD

**Issue by allcodernet** [n4ze3m/page-assist#222]
When I request the page with Copilot, it does the same page data over and over again, just like it does with web-search, when it should do it once. 

![Screenshot from 2024-10-24 18-49-53](https://github.com/user-attachments/assets/1afaf2b3-2492-4b89-b5a2-4da3ccff4ba9)

**Comment by n4ze3m** [comment]
Four citations from the same source are displaying because Page Assist uses a technique that splits large amounts of data into smaller chunks for RAG. The citations are currently set to open in a new tab, but I will update this so that clicking them opens a modal showing the parts sent to the LLM.
