### ISSUE TITLE
Support Brave Search offical API

### ISSUE THREAD

**Issue by nonetrix** [n4ze3m/page-assist#226]
Brave Search never seems to work for me in page assistant, which is something that maybe could be fixed by itself. But regardless, Brave has a official API
https://brave.com/search/api/

**Comment by n4ze3m** [comment]
I'm reworking the Manage Search section :) Mode customization is coming in future updates.

**Comment by n4ze3m** [comment]
Added in the 1.3.8 release :) Closing this; feel free to reopen if you encounter any issues.
