### ISSUE TITLE
can't get gemini nano to run with page assist on chrome v130 on win11

### ISSUE THREAD

**Issue by pleabargain** [n4ze3m/page-assist#227]
on chrome v 130

I followed the instructions:
In order to use Chrome AI, you need a browser version greater than 127, which is currently in the Dev and Canary channels. After downloading the supported version, follow these steps:

Go to chrome://flags/#prompt-api-for-gemini-nano and select "Enable".
Go to chrome://flags/#optimization-guide-on-device-model and select "EnabledBypassPrefRequirement".
Go to chrome://components, search for "Optimization Guide On Device Model", and click "Check for Update". This will download the model. If you don't see the settings, repeat steps 1 and 2 and relaunch your browser.

I followed the steps. no joy

Here's a vid showing all steps
https://youtu.be/NxKXcMgiz5k

thank you

**Comment by n4ze3m** [comment]
Hey, first of all, thanks for your sponsorship!

The Gemini Nano is not fully stable. Two weeks ago, it was working fine, but now it's showing an error. I’ll investigate what's happening. Thank you for the video.

I’ll let you know once it’s fixed. Thanks!

**Comment by n4ze3m** [comment]
Sorry, guys. This issue may take longer to fix since Chrome changed the APIs. :/ I’ll let you know if there are any updates

**Comment by n4ze3m** [comment]
The issue has been fixed. Please let me know if it's working or not. :)

**Comment by pleabargain** [comment]
No joy. 

Go to chrome://flags/#prompt-api-for-gemini-nano and select "Enable".
Go to chrome://flags/#optimization-guide-on-device-model and select "EnabledBypassPrefRequirement".
Go to chrome://components, search for "Optimization Guide On Device Model", and click "Check for Update". 

![image](https://github.com/user-attachments/assets/0fdddc9f-d4d1-4ebd-bb9a-aec7a8a21661)

![image](https://github.com/user-attachments/assets/181422b9-1c0d-4276-9b61-4a1359e004be)

"Optimization Guide On Device Model" doesn't exist on my v. of chrome after reinstalling chrome: "Optimization Guide On Device Model"
Optimization Guide On Device Model is missing after doing steps 1 and 2 and restarting


chrome://settings/help
v of chrome
Version 131.0.6778.70 (Official Build) (64-bit)

**Comment by n4ze3m** [comment]
Hey, can you select EnabledBypassPrefRequirement from these settings?

![image](https://github.com/user-attachments/assets/af0df331-3094-4835-ac73-d91dedf19383)

**Comment by pleabargain** [comment]
still not joy
https://youtu.be/fmqupjXqLGQ

**Comment by stanthewizzard** [comment]
same

**Comment by Tobe2d** [comment]
Same here ;-(

**Comment by mrdjohnson** [comment]
If it helps; nano is working for me on canary: macos 
<img width="727" alt="image" src="https://github.com/user-attachments/assets/9b019e0f-0cce-4630-8a9d-1e510d417ea8">

I've found that gemini does NOT work on chrome dev though :/ only chrome canary.

**Comment by Tobe2d** [comment]
> If it helps; nano is working for me on canary: macos <img alt="image" width="727" src="https://private-user-images.githubusercontent.com/6767910/392030970-9b019e0f-0cce-4630-8a9d-1e510d417ea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNDczMjgsIm5iZiI6MTczMzI0NzAyOCwicGF0aCI6Ii82NzY3OTEwLzM5MjAzMDk3MC05YjAxOWUwZi0wY2NlLTQ2MzAtOGE5ZC0xZTUxMGQ0MTdlYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMTczMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQxZWU4MzNkNzkwMWFiN2E2OTEyNjY0NmE5YWRmNmQ4YjRlNzZkY2Y5ODY2NzgzMzZkMjFhODdiZmIyMmJhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-OmxfqiHmFLnaGdSKHrOPHgfcgW64tXyKqMDKcU_bMM">
> 
> I've found that gemini does NOT work on chrome dev though :/ only chrome canary.

How did you get it to work?

**Comment by mrdjohnson** [comment]
- I had already followed the steps to turn gemini on [here](https://docs.google.com/document/d/1VG8HIyz361zGduWgNG7R_R8Xkv0OOJ8b5C9QKeCjU0c/edit?tab=t.0#heading=h.witohboigk0o)

 but after some time away from it I ran this in my chrome developer console `(await ai.languageModel.capabilities()).available` and it said "no" even though it used to be yes for sure. 
 
 so in chrome dev console I ran `await ai.languageModel.create()` to force it to renew itself, after a few minutes (maybe redownloading?). it started working again. I was using the [Playground](https://chrome.dev/web-ai-demos/prompt-api-playground/) to verify that I even had gemini running as well. if its not working there, its probably broken everywhere

**Comment by marcelol** [comment]
Still broken as of Chrome 138.0.7204.97...figured I'd update this bug to make everyone aware:


I can enable the flags:

chrome://flags/#prompt-api-for-gemini-nano and select "Enable".
chrome://flags/#optimization-guide-on-device-model and select "EnabledBypassPrefRequirement".

but  "_Optimization Guide On Device Model_" is **no longer present** under chrome://components
to even check for updates.

The "_Enable or Disable Chrome AI Support on Page Assist"_ option is disabled completely as a result and cannot be enabled.

**Comment by lemieszek** [comment]
Update to Chrome API that may be the isssue here.
`LanguageModel.create()` is a new API to get to Gemini nano

`ai.languageModel` is no longer to be found.

**Comment by n4ze3m** [comment]
Gemini Nano APIs seem stable now. I’ll update Page Assist in the next version ,it should work fine after that :)
