### ISSUE TITLE
Enhancement: Unique RAG Ollama Instance URL

### ISSUE THREAD

**Issue by lewismacnow** [n4ze3m/page-assist#237]
As the title suggests, I propose you add functionality to support using a unique RAG Ollama URL.
The outcome of this would mean inference and embedding requests could be sent to different hosts.

**Comment by n4ze3m** [comment]
Yes, this is our most requested feature. I will try to add it in this week's update

**Comment by n4ze3m** [comment]
Now you can add multiple Ollama instances via OpenAI API-compatible settings. :)

![image](https://github.com/user-attachments/assets/f0694ca3-e8ec-44f2-89b9-0591f4b9c171)
