### ISSUE TITLE
Cant connect to LAN server

### ISSUE THREAD

**Issue by makedir** [n4ze3m/page-assist#240]
The addon wont connect to Ollama running on another PC in my lan. Locally 127.0.0.1 it works fine, but not form other PCs in the same LAN.

http://127.0.0.1:11434 + page-assist on same PC = working
other pc in same LAN, setting to http://192.168.8.12:11434  = not working

![grafik](https://github.com/user-attachments/assets/6fdb700f-41ec-404a-8122-a0a3b5bc4d97)

![grafik](https://github.com/user-attachments/assets/0ec79b93-c883-496b-a268-2bf57ef3efe3)

It seems Ollama is configured by default to just allow local access to 127.0.0.1 but not binding on lan adapter. Why isnt this in the howto or mentioned anywhere in your addon and how to solve it?

**Comment by makedir** [comment]
Update:

You need to add this:

https://github.com/ollama/ollama/blob/56318fb365be38253fc9abeeabc850d01be2521a/docs/faq.md#how-do-i-configure-ollama-server

OLLAMA_HOST=0.0.0.0

![grafik](https://github.com/user-attachments/assets/4669a64d-7e3e-4417-866a-c62020340f11)


Maybe you should add this to https://github.com/n4ze3m/page-assist/blob/main/docs/connection-issue.md

**Comment by n4ze3m** [comment]
Hey, sorry about the issue. I'll update the documentation
