### ISSUE TITLE
Tried using "llama3.2-vision:latest" (11B) vision feature, but get the Cannot read properties of undefined (reading 'content') error.

### ISSUE THREAD

**Issue by lgrando1** [n4ze3m/page-assist#243]
Congrats for this great work. This is a great tool. Thanks so much.

I tried to using the new llama3.2-vision:latest and get this error:

"Error Cannot read properties of undefined (reading 'content')"

My computer is a Intel core i5 9300H laptop, 16GB of ram and a GTX 1650.

Again, thanks so much.

**Comment by n4ze3m** [comment]
Hey, sorry about the issue. Did you try the vision model on the sidebar or web UI?

**Comment by lgrando1** [comment]
Hi, N4ze3m. I tried in the web UI. I tried again and the error didn't happen more. 

As my GPU is only a 4GB vRAM, they is running in 100% CPU. 

![image](https://github.com/user-attachments/assets/b3796f18-b7d5-4cf2-b6a7-4f8a22d9887c)

You work here is wonderful... and thanks for your attention.
