### ISSUE TITLE
useMmap config like in continue

### ISSUE THREAD

**Issue by xgdgsc** [n4ze3m/page-assist#259]
useMmap like in continue extension :
```
 {
        "model": "AUTODETECT",
        "title": "Autodetect",
        "provider": "ollama",
        "completionOptions": {
            "keepAlive": 9999999,
            "useMmap": true
        }
    }
```
How to specify this ollam option?

**Comment by n4ze3m** [comment]
I think I missed a few Ollama model configurations. I will add them in the next updates. 😊

**Comment by n4ze3m** [comment]
The useMmap setting was added in the last version. Closing this. Feel free to reopen or create a new issue if you encounter any problems.
