### ISSUE TITLE
Missing URL

### ISSUE THREAD

**Issue by Deobot2** [n4ze3m/page-assist#26]
Hey! love this project and have been messing around with it for a while. was looking to page share but couldn't resolve: https://github.com/n4ze3m/page-assist-app.git
i assumed
https://github.com/n4ze3m/page-share-app
is what you were referring to so i went and tried to make a docker of said repo. i received an error telling me that it couldn't find the .env file. i resorted to Railway but that also failed. i have tried troubleshooting but couldn't figure it out. For context i have basic experience with ubuntu(what I'm trying to run docker on) and no experience with docker so i might have missed a silly mistake.
Would appreciate any help thanks in advance.

**Comment by n4ze3m** [comment]
Hey, sorry about that. There was an issue in the docker-compose file, but it has been resolved. Just clone the repo and run `docker-compose up`, that's all. Please let me know if you still encounter any issues.

**Comment by Deobot2** [comment]
fixed! thanks!
