### ISSUE TITLE
Feature: Keyboard shortcuts in MacOS do not work

### ISSUE THREAD

**Issue by didikrm** [n4ze3m/page-assist#27]
Tried different combinations of keys (Control, Option, Command and Shift) but I don't think there are ready mappings.

**Comment by n4ze3m** [comment]
Hey, I will fix it in the upcoming release. Additionally, you can change the default shortcut from `chrome://extensions/shortcuts`

![image](https://github.com/n4ze3m/page-assist/assets/39720973/07f03793-075f-4c1b-9bb6-870ee3694d2f)
