### ISSUE TITLE
Add Llama File support

### ISSUE THREAD

**Issue by aiseei** [n4ze3m/page-assist#44]
This would massively valuable in terms of accessing small models with min infra. 
https://github.com/Mozilla-Ocho/llamafile

**Comment by n4ze3m** [comment]
Hey, this is the first time I'm hearing about Llamafile. I will look into how to add support to page assist :)

**Comment by n4ze3m** [comment]
Page Assist now supports the LlamaFile API out of the box. Just add it to the OpenAI API-compatible settings
