### ISSUE TITLE
Republishing Page Assist with a New Name and Additional Features

### ISSUE THREAD

**Issue by saliksik** [n4ze3m/page-assist#46]
I plan to republish this extension, Page Assist, on the Chrome Web Store under a different name and with some additional features tailored for my specific use case with co-workers, friends, and family. However, I want to emphasize that the core functionality and the open-source nature of the project will remain unchanged.

## Reasons for Republishing:

- **Specific Use Case:** The added features will be highly customized for my group, potentially making the extension less relevant for the broader public on the Chrome Web Store.
- **Sharing and Collaboration:** Republishing allows me to easily share the extension within my circle through the Chrome Web Store, promoting efficient collaboration.

## Commitment to Open Source:

- The project will remain open source under the existing MIT License.
- The source code will continue to be available on GitHub for anyone to use, modify, and contribute to.
- I encourage users to fork the repository and adapt it to their own needs.

## Changes in the Republished Version:

**Name Change:** The extension will have a new name to distinguish it from the original Page Assist.
**Additional Features:** Specific functionalities will be added to cater to the needs of my intended user group.

## Transparency and Communication:

I believe in open communication and want to assure the community that this republishing effort is not intended to fragment the project or limit its accessibility. 

I welcome any questions or feedback regarding this decision. Please feel free to leave a comment or open a discussion if you have any concerns or suggestions.

**Comment by n4ze3m** [comment]
Page Assist is open source and free. Feel free to do anything; I'm totally happy 😄
