### ISSUE TITLE
Page Share

### ISSUE THREAD

**Issue by VideoFX** [n4ze3m/page-assist#53]
How do I disable page share for privacy reasons?

It is "https://pageassist.xyz" by default, but I cannot change it. When I try to change it to something like "none" it says "failed to fetch".

Would is be possible for me to disable sharing?

**Comment by n4ze3m** [comment]
Hey, I will add an option to disable the page share feature in the next update. Currently, you can change the page share URL to a self-hosted version.

**Comment by n4ze3m** [comment]
Hey, in the 1.1.5 update, there will be an option to disable page share

**Comment by VideoFX** [comment]
Very nice work on this!! Thank you for sharing this with us!
