### ISSUE TITLE
Manifest error - Permission 'action' is unknown or URL pattern is malformed.

### ISSUE THREAD

**Issue by aiseei** [n4ze3m/page-assist#58]
Hi 

Thanks for your great work!
When I build locally without errors and when I try to load the extension from chrome-mv3 folder- I get 
"Permission 'action' is unknown or URL pattern is malformed" and 

"Uncaught (in promise) Error: Invalid `workerSrc` type."

Is there something I am missing ?

Thanks!

**Comment by n4ze3m** [comment]
This error/warning occurs only in the development environment, as far as I know, and the extension should work fine

**Comment by aiseei** [comment]
ok. What can do to fix it ? Please advise

**Comment by aiseei** [comment]
Fixed it. Thanks!
