### ISSUE TITLE
Allow  options to be sent to Ollama

### ISSUE THREAD

**Issue by aiseei** [n4ze3m/page-assist#59]
Hi!
It would be great if options items such as context, temperature, etc can be set for a prompt and conversation for a prompt. 

Finding this very useful!

Regards,

**Comment by n4ze3m** [comment]
Hey, model parameter settings have been added in the v1.1.10 release. There are two ways to configure it: one, globally in the Ollama settings, and two, for the current chat by clicking the brain with the cog icon in the header

![image](https://github.com/n4ze3m/page-assist/assets/39720973/a998402e-2c7a-429e-b946-40148b85a907)
![image](https://github.com/n4ze3m/page-assist/assets/39720973/8228c921-54e1-439f-92a2-0c3eb57a15c3)

**Comment by aiseei** [comment]
Thanks @n4ze3m !
Looks good. Given the number of params that can be used and the limited space on the UI. Can I suggest that you allow use to paste a dictionary of params that can be appended to options ==> "options":{"num_ctx":32000,"temperature":0.7} in the request. This is obviously for someone who needs that level of control with the downside that the extension cant validate the types for the additional params.
