### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by gerroon** [n4ze3m/page-assist#61]
Hi

Do you have a rough timeline for the FF support? I saw that it is in the roadmap. As far as I can tell there are no FF extensions that helps with locally tunning LLMs

**Comment by n4ze3m** [comment]
I'm working on it. It needs to do a few migrations in order for the extension to work on both Chrome and Firefox. Hopefully, the Firefox version will be released this weekend or next week

**Comment by gerroon** [comment]
Amazing thanks for the hard work

**Comment by n4ze3m** [comment]
Hey, guys, Page Assist now officially supports Firefox. 

You can download the extension from the Firefox add-on store: https://addons.mozilla.org/en-US/firefox/addon/page-assist/ 

Please let me know if you face any issues.

**Comment by gerroon** [comment]
Thanks, that is great. Is it possible to put the assistant window on the right instead of the left by default?
