### ISSUE TITLE
Suggestion: Add support for LiteLLM

### ISSUE THREAD

**Issue by ginto-sakata** [n4ze3m/page-assist#67]
Hi Muhammed and thank you for this awesome tool.
Can you add support for LiteLLM? I want to use llama 70B with Groq so I can be not dependent on running ollama.

**Comment by n4ze3m** [comment]
Hey, LiteLLM is Python-based and won't work with a browser extension, I think. But I already created a fork of the Page Assist project which supports third-party AI providers like OpenAI, Groq, Fireworks, etc.

Repo: https://github.com/n4ze3m/dialoqbase-lite 

Extension: https://chromewebstore.google.com/detail/dialoqbase-lite-a-sidepan/fhdonbcklgialicndhegpkkhhekafglb

**Comment by ginto-sakata** [comment]
Thank you, i'll try it
