### ISSUE TITLE
The dropdown list of Models on the main page is empty

### ISSUE THREAD

**Issue by danny-su** [n4ze3m/page-assist#7]
The dropdown list of Models on the main page is empty, in fact, I've installed several models.

<img width="201" alt="91144" src="https://github.com/n4ze3m/page-assist/assets/12178855/65854af3-3fe2-4fad-a84d-3daf83f4caa5">

The dropdown list of the Embedding Model has been filled.
<img width="190" alt="53603" src="https://github.com/n4ze3m/page-assist/assets/12178855/91ad3163-2972-477d-b643-346805bf3f9c">

**Comment by danny-su** [comment]
<img width="871" alt="image" src="https://github.com/n4ze3m/page-assist/assets/12178855/1c89b802-0f3f-4ab8-838b-92d164c2e39d">

**Comment by n4ze3m** [comment]
Sorry about that. I will release a fix now.

**Comment by n4ze3m** [comment]
Hey, a fix has been released. It will update the Chrome Web Store within 2-8 hours

**Comment by n4ze3m** [comment]
v1.0.4 has been released. Please let me know if you still encounter any errors. :)

**Comment by danny-su** [comment]
@n4ze3m Thanks, it works now.
