### ISSUE TITLE
Custom search language

### ISSUE THREAD

**Issue by chllei** [n4ze3m/page-assist#71]
Thanks for developing such a useful plugin. Whether it would be possible to add an option that allows users to switch the language used during online searches? For instance, when searching for advancements in a specific field, I'd prefer using English for online searching; however, when looking for information about certain tourist attractions in China, I might find it more convenient to use Chinese for online searches.

**Comment by n4ze3m** [comment]
Yes, we will add an option to change the search engine URL soon.
