### ISSUE TITLE
Unable to select model

### ISSUE THREAD

**Issue by kaustuvchatterjee** [n4ze3m/page-assist#75]
I am unable to select the model. On clicking a model in the dropdown box nothing happens.
OS: Fedora 39
Browser: Brave, Chrome

**Comment by n4ze3m** [comment]
Hey, sorry about that. Is the issue on both the web UI and the side panel right? I will look into it

**Comment by kaustuvchatterjee** [comment]
It was an issue with both the web UI and the side panel. However, after re-installing Ollama the issue was resolved. I had last installed Ollama about 5 months back.

**Comment by n4ze3m** [comment]
Happy :) I will add the minimum Ollama version to the README and extension description. I'm closing the issue. Feel free to open a new one if you have any issues with Page Assist. Thanks.
