### ISSUE TITLE
FR: Arrow Up to edit last entry

### ISSUE THREAD

**Issue by gerroon** [n4ze3m/page-assist#76]
Hi

it would be great if one could use the arrow up button to edit the last user entry (not the reply from the model) to repost as a new message. This is  a feature in many chat apps.

thanks

**Comment by n4ze3m** [comment]
Hey, currently you can edit all messages, not the last message. Do you mean a button which will go to the last user message instead of scrolling?

![image](https://github.com/n4ze3m/page-assist/assets/39720973/334335a5-961c-4200-9c94-40ac50d8c1ba)

**Comment by gerroon** [comment]
I do not see  a way to edit it? But that was not what I meant, using "arrow up" will rputt the last user entry in the message box, so it can be posted as a new entry

**Comment by n4ze3m** [comment]
Got it! :) I'll try to add it.

**Comment by n4ze3m** [comment]
Hey, I have fixed a few side panel bugs you suggested. Now, it has edit and regenerate buttons, and the copy button of the last message is now visible.

**Comment by gerroon** [comment]
> Hey, I have fixed a few side panel bugs you suggested. Now, it has edit and regenerate buttons, and the copy button of the last message is now visible.

Thank you awesome person, I will test them out.
