### ISSUE TITLE
Missing copy and speak buttons in Firefox

### ISSUE THREAD

**Issue by gerroon** [n4ze3m/page-assist#78]
Hi

The chat window does not show the copy and the read aloud buttons when the mouse is overt if the response it at the bottom of the window, see the image please

Thanks

![image](https://github.com/n4ze3m/page-assist/assets/8519469/b10c0c5c-bf7d-4791-8d42-b3ae0eedf89a)

**Comment by n4ze3m** [comment]
It's because of a styling issue, I guess. I will fix it

**Comment by gerroon** [comment]
> Hey, most of the issues you reported from the Page Assist side panel on Firefox, right?

Yes, thanks for asking

**Comment by gerroon** [comment]
Hi

Thanks for the fixes, they made the extension more usable. Is it also possible to select text in the side bar without going into the edit mode just like in the Chrome version? Right now it is not possible to select any text in the side bar in Firefox.
