### ISSUE TITLE
[SUGGESTION] Replace the font family by a more readable one

### ISSUE THREAD

**Issue by Lathanao** [n4ze3m/page-assist#80]
First, thank you for the extension, looks very great. For sure, I will use it many time.
Please check this screen shot, one is far more readable than the other one. IMHO, the font family "Inter", on the right side, is not the best for doing the job. The default system font looks far better on my screen.

![image](https://github.com/n4ze3m/page-assist/assets/6756795/3b07491f-6d01-4f7d-a0f6-7bb53640f49c)

**Comment by n4ze3m** [comment]
Thanks for the suggestions. I will add an option to select font

**Comment by Lathanao** [comment]
Thank for the change. Got the update. New font is far better!
