### ISSUE TITLE
Whenever we close sidemenu in firefox it reset the chat session of it so we cant further follow conversation on that ongoing topic in side menu

### ISSUE THREAD

**Issue by HakaishinShwet** [n4ze3m/page-assist#84]
Conversation of side menu should not reset as we might want full page view for reading properly and then asking and then closing side menu and then opening and asking followup question or query so if chat session gets reset then we cant followup on conversation so its not great experience so what can be done  in my opinion is give chat clear option/button which people can press if they want to reset/start from scratch else can continue with same side menu chat session. So with this we can give option to start new chat session plus if we dont wanna reset chat and followup on convo we can do that by default.

**Comment by n4ze3m** [comment]
This is a great feature, but some people prefer a new chat when opening the side panel. The best way to address this is to add a new setting to choose whether to show the previous chat or not

**Comment by HakaishinShwet** [comment]
@n4ze3m nice :-)) will be waiting for it

**Comment by n4ze3m** [comment]
Hey, the side panel (Copilot) can now resume previous chats. You can enable it in the settings

https://github.com/n4ze3m/page-assist/assets/39720973/b6f829d5-1393-49e1-aaa5-8ff09b9f65cf

**Comment by HakaishinShwet** [comment]
@n4ze3m  niceee, perfectly working as i expressed above
Thankyou very much :-))
