### ISSUE TITLE
[FEATURE SUGGESTION] Add Brave Search as an option for the search providers

### ISSUE THREAD

**Issue by JoshuaKimsey** [n4ze3m/page-assist#87]
search.brave.com is definitely my favourite search engine currently, so thought it would be cool to have it as an option along with Google, DDG, etc. To do so is fairly straight forward, it's just: `search.brave.com/search?q=%s`, so hopefully it wouldn't be too hard to add? :)

**Comment by n4ze3m** [comment]
Thank you for the suggestion. I will add the Brave search. :)

**Comment by n4ze3m** [comment]
Hey, Brave Search has been added in v1.1.10.
