### ISSUE TITLE
[FEATURE SUGGESTION] Add the ability to do internet searches from from the side panel

### ISSUE THREAD

**Issue by JoshuaKimsey** [n4ze3m/page-assist#89]
I noticed that the toggle to do internet searches is only available when using Page Assist in it's own tab. I definitely understand not wanting that an as option when chatting with a web page, but for other tasks not using that, it would be quite convenient to have that be usable from the side panel for quick availability!

**Comment by n4ze3m** [comment]
Internet search is now available in the sidebar. I'm closing this issue, thanks.
