### ISSUE TITLE
Ability to change keep_alive setting

### ISSUE THREAD

**Issue by vec137** [n4ze3m/page-assist#90]
I noticed that my model is automatically offloaded from memory due to the 'keep_alive' parameter that is sent to the server. Could you please add the ability to edit or disable it, as the parameter passed through environment variables is automatically overrode by yours?
![2024-05-20T14:02:31,022273693+03:00](https://github.com/n4ze3m/page-assist/assets/135970206/a15ee470-ab10-4aa3-8b11-dad2f1227025)

**Comment by n4ze3m** [comment]
I will add a new option for models on the Ollama settings page

**Comment by vec137** [comment]
thank you a lot :)

**Comment by n4ze3m** [comment]
Hey, model parameter settings have been added in the v1.1.10 release. There are two ways to configure it: one, globally in the Ollama settings, and two, for the current chat by clicking the brain with the cog icon in the header

![image](https://github.com/n4ze3m/page-assist/assets/39720973/a998402e-2c7a-429e-b946-40148b85a907)
![image](https://github.com/n4ze3m/page-assist/assets/39720973/8228c921-54e1-439f-92a2-0c3eb57a15c3)

**Comment by vec137** [comment]
Thanks :)
