### ISSUE TITLE
[Question]: Accessing Ollama from remote machine

### ISSUE THREAD

**Issue by bri6935** [n4ze3m/page-assist#91]
Hello - was going through the documentation but couldnt find if i just have the wrong setup/address or it really would not work.
I have ollama running on my Mac studio, and have a macbook air to access it (using an app called enchanted), and its ngrok thats pushing it online.
When i try to use it with page-assist i have this error:

<img width="607" alt="Screenshot 2024-05-21 at 9 22 19 AM" src="https://github.com/n4ze3m/page-assist/assets/22981037/17210c74-d843-4853-847b-926e5e9da48f">

I could see its trying to connect but being kicked out. 

<img width="537" alt="Screenshot 2024-05-21 at 9 24 46 AM" src="https://github.com/n4ze3m/page-assist/assets/22981037/8d9694f1-d104-4ea5-bdcf-be4126d2e2c8">

Do i need to modify anything on the ngrok address?

(big fan, this is my favorite ollama ui on my main machine :-)

**Comment by n4ze3m** [comment]
Hey, did you try enabling the custom URL origin from the settings? If not, all you need to do is go to Settings > Ollama Settings and enable the custom origin URL. Hopefully, this will resolve the issue.


for more details: https://www.youtube.com/watch?v=fydtRnxjfJU or https://github.com/n4ze3m/page-assist/blob/main/docs/connection-issue.md#solutions

![image](https://github.com/n4ze3m/page-assist/assets/39720973/dedb8e55-dc6f-41f5-8b00-f7c3dcd84ab8)

**Comment by bri6935** [comment]
Hello! thanks for the reply. I did (screenshots below). but i have a feeling now that it has nothing to do with pageassist but rather how ngrok (and im guessing similar services) will handle ollama when being accessed remotely. I can see its trying to but being kicked out. Will also check the other apps that are working (OpenWebui and Enchanted) and have a look at the code how they are calling a remote machine/ngrok

Ill poke around and will update here if i get it to work :-)

[my actual endpoint isnt the below, just illustrating the settings]
<img width="917" alt="image" src="https://github.com/n4ze3m/page-assist/assets/22981037/5800baf5-324c-4b0e-922a-45e0b97c9aad">

<img width="682" alt="image" src="https://github.com/n4ze3m/page-assist/assets/22981037/ecf68ec2-2d5f-4ed6-9ede-b5b5572ff4de">

**Comment by n4ze3m** [comment]
Hey, can you change the custom origin URL to `http://localhost:11434` ?

**Comment by bri6935** [comment]
That worked!

1. In Ollama URL-> the ngrok/remote enpoint 
2. in the Custom origin, "http://localhost:11434"

screenshot below. mac air calling the studio :-)

thank you! 

<img width="979" alt="image" src="https://github.com/n4ze3m/page-assist/assets/22981037/563c7d09-1693-4f71-9688-7c24dbdad770">

**Comment by n4ze3m** [comment]
😀
